#CREATE THIS IN THE NAMESPACE WHERE THE DESTINATION DEPLOYMENT OR POD IS SITTING ON
#LABEL THE NAMESPACES OF THE DEPLOYMENTS [oc label namespace <NAMESPACE NAME> network=<LABEL VALUE)]  --> EG: oc label namespace different-namespace network=different-namespace

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-specific
spec:
  podSelector:
    matchLabels:
      deployment: <name of the deployment you want to allow traffic to (destination)>
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            network: <label of the namesapce of where the deployment or pod is sitting on>
        podSelector:
          matchLabels:
            deployment: <deployment name of the pod you want to talk to the other deployment (source)>
      ports:
      - port: <port number>
        protocol: <define the protocol>
